project_name: "grpo-qwen3_14b-kernelbench"
run_name: "rl-locking"
clean_start: true

hydra:
  job:
    chdir: false

prompt:
  system_prompt: "src.train.prompts.task_conditional.txt"

model:
  name: "Qwen/Qwen3-14B"
  torch_dtype: "bfloat16"
  use_cache: false

reward:
  training_mode: "locking"      # "elicitation", "locking"
  seed: 42
  timeout: 60
  n_runs: 1
  include_runtime_reward: false
  verbose: true

dataset: 
  name: "ScalingIntelligence/KernelBench"
  split: "level_1"
  limit: 100
  target_key: "code"
  think_token: "/think"
  apply_prompt_fn: "src.prompt_constructor.prompt_generate_custom_cuda_from_prompt_template"

io:
  original_src_dir: "./original_src"
  target_src_dir: "./target_src"

gpu_arch: 
  - "Hopper"

grpo:
  temperature: 1.0
  top_p: 0.95
  lr : 1e-4
  bf16: true
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 4
  generation_batch_size: 32
  num_generations: 8
  max_prompt_length: 1536
  max_completion_length: 8192
  max_steps: 500
  logging_strategy: "steps"
  logging_steps: 1
  logging_first_step: true
  save_steps: 10
  report_to: "wandb"
  ddp_find_unused_parameters: true
  ddp_broadcast_buffers: false
  remove_unused_columns: false
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false
  vllm:
    use_vllm: true
    # vllm_mode: "colocate"
    vllm_mode: "server"
    vllm_server_base_url: "http://127.0.0.1:8000"
    vllm_gpu_memory_utilization: 0.8
    # vllm_server_timeout: 1800

  # adam_beta1: 0.9
  # adam_beta2: 0.99
  # weight_decay: 0.1
  # warmup_ratio: 0.1
  # lr_scheduler_type: "cosine"
  # optim: "paged_adamw_8bit"

lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0
  bias: "none"
  task_type: "CAUSAL_LM"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"